export const data = [
    {
      question: "Which device is required for the Internet connection?",
      option1: "Modem",
      option2: "Router",
      option3: "LAN Cable",
      option4: "Pen Drive",
      ans: 1,
    },
    {
      question: "which continent has the highest number of countries?",
      option1: "Asia",
      option2: "Europe",
      option3: "North America",
      option4: "Africa",
      ans: 4,
    },
    {
      question: "Junk e-mail is also called?",
      option1: "Spam",
      option2: "Fake",
      option3: "Archieved",
      option4: "Bin",
      ans: 1,
    },
    {
      question: "A computer cannot BOOT if it does not have the?",
      option1: "Application Software",
      option2: "Internet",
      option3: "Operating System",
      option4: "Mouse",
      ans: 3,
    },
    {
      question: "First page of website is termed as?",
      option1: "Index Page",
      option2: "Homepage",
      option3: "Sitemap",
      option4: "Pen Drive",
      ans: 2,
    },
    {
      question: "Which element is the most abundant in the Earth's Crust?",
      option1: "Iron",
      option2: "Silicon",
      option3: "Aluminum",
      option4: "Oxygen",
      ans: 4,
    },
    {
      question: "Which desert is the largest in the world?",
      option1: "Sahara Desert",
      option2: "Carcross Desert",
      option3: "antarctic polar Desert",
      option4: "Great Indian Desert",
      ans: 3,
    },
    {
      question: "What is the chemical symbole for water?",
      option1: "N2",
      option2: "O2",
      option3: "H2O",
      option4: "H2",
      ans: 3,
    },
    {
      question: "Which planet is known as the Red planet?",
      option1: "Juputer",
      option2: "Mars",
      option3: "Earth",
      option4: "Mercury",
      ans: 2,
    },
];